# # # X=['APPLE','AKASH','KSHITISH',7,8.52,False]
# # # print(X)
# # # print(type(X))


# # l1=[1,4,3,'kshitish']
# # # print(l1[0])
# # # print(l1[3])
# # # print(l1[7])  #list our of the range
# # print(l1[-4:0])

# l1=[1,4,3,143,420]
# print(l1)
# print(type(l1))
# # l1.sort()
# # l1.reverse()
# # l1.append(12)
# # l1.append(20)
# # l1.insert(0, 50)
# # l1.pop(4)
# l1.remove(420)
# print(l1)

kshitish=(1,4,3,143,420,1,4,12,3,420,420,3,9)
# kshitish=()
# kshitish=(1,)
# kshitish=(1,2,3)
# kshitish=print(kshitish.count(9))
kshitish=print(kshitish.index(9))
# print(kshitish)
